[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace STM32G071C8Rx with your chip as listed in `probe-run --list-chips`
runner = "probe-run --chip STM32G070CBTx"

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "trace"
